### PR TITLE
Converter script for .hic to hseq

### PR DESCRIPTION
**Pull request by cvaske**
This script converts the well-established .hic file format into the HoloSeq hseq format using the
[straw](https://github.com/aidenlab/straw/) library. The hic format
stores a symmetric matrix, and the converter only provides the lower
triangle of counts to distinguish it from asymmetric matrices.

The hseq data format is described here:
https://github.com/holoviz-topics/holoSeq/blob/main/docs/HoloSeqOverview.md

## Usage:

1. Install the required dependency:
   ```
   pip install hic-straw
   ```

2. Download a .hic file. For example, in the series
   [GSE207951](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE207951),
   click on "(custom)" in the table at the bottom, check a single .hic
   file, then click the "Download" button. Untar it.

3. Run the conversion script:
   ```
   python3 scripts/hic2hseq.py input.hic output.hseq.gz
   ```

4. Use the output file in the HoloSeq environment to display the matrix:
   ```
   panel serve scripts/holoseq_display.py --show --args --inFile output.hseq.gz --size 1000
   ```

## Example Data:

A pre-converted HTAN file for [GSM6326543 is
available (530MB)](https://pub-867b121072f54b4a9eecdf01cd27246b.r2.dev/GSM6326543_A001C007.hg38.nodups.pairs.hseq.gz).

See hseq conversion output of GSM6326543 at `holoseq/docs/assets/README_GSM6326543.png`

README_GSM6326543

### CODE REVIEW

**Review by droumis — APPROVED** [review]
@cvaske throwing the review back to you after refactoring and reorganizing into the scripts dir.. please run the conversion now to confirm and then merge if you're happy with this

**Comment by droumis** [comment]
@cvaske, could you also please add a one sentence motivation/context at the top of the PR description for those less aware of this domain

**Comment by cvaske** [comment]
The script worked great, however I moved the dependency on `hic-straw` to the pyprojec.toml since we now have a proper package. Requesting review to make sure that's the best place for the dependency.

**Review by droumis — APPROVED** [review]
LGTM!

**Pull request merged**
